name: CodSpeed Benchmarks

on:
  push:
    branches:
      - "main" # or "master"
  pull_request:
  # `workflow_dispatch` allows CodSpeed to trigger backtest
  # performance analysis in order to generate initial data.
  workflow_dispatch:

permissions: # optional for public repositories
  contents: read # required for actions/checkout
  id-token: write # required for OIDC authentication with CodSpeed

jobs:
  benchmarks:
    name: Run benchmarks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      # Setup CMake version 4.2
      - name: Setup CMake
        uses: lukka/get-cmake@latest
        with:
          cmakeVersion: "4.2.x"

      - name: Build the simulation benchmark target(s)
        run: |
          cmake -B simulation_build -S . -DCODSPEED_MODE=simulation
          cmake --build simulation_build -j $(nproc)

      - name: Build the walltime benchmark target(s)
        run: |
          cmake -B walltime_build -S . -DCODSPEED_MODE=walltime
          cmake --build walltime_build -j $(nproc)

      - name: Run the simulation benchmarks
        uses: CodSpeedHQ/action@v4
        with:
          mode: simulation
          run: ./simulation_build/CodSpeedTest

      - name: Run the walltime benchmarks
        uses: CodSpeedHQ/action@v4
        with:
          mode: walltime
          run: ./walltime_build/CodSpeedTest